### ISSUE TITLE
Build problems #2

### ISSUE THREAD

**Issue by spxl** [brucelane/reymenta-mixnmap#4]
Trying again to build from the instructions at https://github.com/brucelane/reymenta-mixnmap

Compile
- use visual studio 2013
- download Cinder glNext branch from https://github.com/cinder/Cinder/tree/glNext
- download these Cinder blocks (glNext branch): MinimalUI(https://github.com/nselikoff/Cinder-MinimalUI/tree/glNext), openCV(https://github.com/cinder/Cinder-OpenCV/tree/dev), Warping (https://github.com/paulhoux/Cinder-Warping/tree/glNext), Spout(https://github.com/brucelane/Cinder-Spout/tree/glNext)

Guessing where to put files:

My base Cinder folder ($CINDER): C:\data\dev\Cinder\**Cinder-glNext**
- Reymenta project folder: $CINDER\projects\**reymenta-mixnmap-master**
- Boost library folder: $CINDER\**boost**\**boost**
- Blocks placed under: $CINDER\**blocks**
  - Rename $CINDER\blocks\**Cinder-MinimalUI-glNext** to **Cinder-MinimalUI**
  - Rename $CINDER\blocks\**Cinder-OpenCV-dev** to **Cinder-OpenCV**
  - Rename $CINDER\blocks\**Cinder-Spout-glNext** to **Cinder-Spout**
  - Rename $CINDER\blocks\**Cinder-Warping-glNext** to **Cinder-Warping**

In the Solution Explorer:
- delete the **imgui** subtree (no longer used according to notes for [Issue #1](https://github.com/brucelane/reymenta-mixnmap/issues/1#issuecomment-62395860))
- add Blocks/**MinimalUI** filter with /**include**/* and /**src**/* branches
- add Blocks/**Spout** filter with /**include**/* branch
  - Unsure what to do with the /**lib** files, Spout.dll, Spout.lib, SpoutPanel.exe

In the MixMap Propert Pages:
- Set C/C++ > General > Additional Include Directories to:
  - ..\include
  - ..\..\..\include
  - ..\..\..\boost
  - ..\..\..\blocks\Cinder-MinimalUI\include
  - ..\..\..\blocks\Cinder-OpenCV\include
  - ..\..\..\blocks\Cinder-OpenCV\include\opencv2
  - ..\..\..\blocks\Cinder-Spout\include
  - ..\..\..\blocks\Cinder-Warping\include
  - ..\..\..\blocks\OSC\src
- Update the \**Spout**\ reference in Linker > Input > Additional Dependencies to \**Cinder-Spout**\

Having done this... some things that are broken:
- Vec2f, Vec3f, Vec4f, Vec2i, etc not defined (used in MixnMapApp.cpp, ParameterBag.cpp/h)

| Error Description / Code | File | Line |
| --- | --- | --- |
| error C2248: 'cinder::gl::Texture2d::Texture2d' : cannot access protected member declared in class 'cinder::gl::Texture2d' | textures.cpp | 14 |
| gl::Texture img(loadImage(loadResource(IMG))); | " | " |
| error C2661: 'cinder::gl::Fbo::Fbo' : no overloaded function takes 2 arguments | textures.cpp | 21 |
| mFbos.push_back(gl::Fbo(mParameterBag->mFboWidth, mParameterBag->mFboHeight));//640x480 | " | " |
| error C2039: 'setViewport' : is not a member of 'cinder::gl' | textures.cpp | 109 |
| gl::setViewport(mFbos[0].getBounds()); | " | " |
| error C2039: 'unbind' : is not a member of 'cinder::gl::GlslProg' | textures.cpp | 173 |
| aShader->unbind(); | " | " |

**Comment by brucelane** [comment]
hi spxl,
I'm back to developing this software, using Cinder 0.8.6 this time.
I close this issue for now, as a lot has changed, I have to rewrite the setup instructions
thank you for your feedback
